### ISSUE TITLE
Getting passkey not found

### ISSUE THREAD

**Issue by scriptzteam** [WhatCD/Gazelle#100]
Getting passkey not found on Ubuntu 14

anything to resolve this?

**Comment by antonioantunes** [comment]
Check tracker_password, both on ocelot source and on classes/config.php. They should match, if not, passkey not found will happen

**Comment by scriptzteam** [comment]
oke thx ;) now the error gone, i see i seed torrent even in the gazzelle i can see i seed it but when i download torrent from gazzelle i can not see any peers, crontab runs the peer update so do not know

**Comment by scriptzteam** [comment]
On for example transmission i got this (i see there is one seed and 1 leech me but i can not connect to that seed why?):

Last Announce: Today 02:17:10 PM (got 0 peers)
Next announce in 29 minutes
Last Scrape: Today 02:17:10 PM
Seeders:	1
Leechers:	1
Downloads:	0
