### ISSUE TITLE
Switch to an FSF or OSI-approved free software license

### ISSUE THREAD

**Issue by williamtheaker** [WhatCD/Gazelle#2]
It would be cool to see this in major GNU/Linux distributions like Debian and Fedora. Switching to a free software (and hopefully GPL-compatible) license could attract more developers and allow the incorporation of code from other free and open source software projects.

FSF approved licenses: https://gnu.org/licenses/license-list.html#SoftwareLicenses
OSI approved licenses: http://opensource.org/licenses/alphabetical

**Comment by WhatCD** [comment]
Due to the bulk of contributions from unreachable constituents we do not forsee this will be doable - we don't have contact with many of the original authors, and we would need to secure their permission to switch to a more standard free software license.
