### ISSUE TITLE
Ocelot 0.7 Error: Segmentation fault

### ISSUE THREAD

**Issue by riverstore** [WhatCD/Gazelle#47]
Hi! I get the error message: "Segmentation fault" once a day. This error appear when I run with 1879 users and 3360 torrents (I tested with about 20 torrent and 20 users for a long time, the problem not appear). Can anyone please help me. Thanks a lot!

**Comment by WhatCD** [comment]
If this issue persists with release 1.0 please open an issue on the Ocelot repository (https://github.com/WhatCD/ocelot)
