### ISSUE TITLE
Issues / Features You Would Like Community Code

### ISSUE THREAD

**Issue by kkirsche** [WhatCD/Gazelle#53]
Hey Guys,

I was wondering the best way to communicate to find what features / bugs you had that you wanted to add. Without knowing what you want or don't want added, it's hard to add things.

For example, would you be interested in adding two factor authentication to Gazelle?

**Comment by WhatCD** [comment]
Getting in touch with a developer on the site is the best way to contribute currently. We will be making announcements shortly that should make that process easier.
