### ISSUE TITLE
Arbitrary bytes are not accepted as a valid password

### ISSUE THREAD

**Issue by nagisa** [WhatCD/Gazelle#57]
`ꚍḛṎсǂむЋΤϥÅßƧハꜵϟƥǞᾁĢČῄԈՊẮ҅テꝶけんヷ¢ṕ` will not be accepted as a valid password even though it contains uppercase, lowercase characters and symbols and is over 8 characters long and generally is much stronger than ASCII only password.

**Comment by bloot** [comment]
A couple of points against supporting unicode passwords, that I tend to agree with. Just for a reference point behind reasoning for not introducing support ( http://stackoverflow.com/questions/1797777/should-i-support-unicode-in-passwords )

**Comment by nagisa** [comment]
@bloot I changed the issue title to better represent the issue.

**Comment by WhatCD** [comment]
There is not currently a plan to accept arbitrary characters in password data, however, pull requests are welcome.
