### ISSUE TITLE
Can import Torrenttrader database 

### ISSUE THREAD

**Issue by MaximWain** [WhatCD/Gazelle#81]
Can import Torrenttrader database ? , if can how to do it

**Comment by WhatCD** [comment]
Anything is possible with the correct knowledge of MySQL and some PHP fudging.

**Comment by MaximWain** [comment]
Sir , can you help me to do that ?

**Comment by WhatCD** [comment]
No. That is beyond the scope of support for the project, which is bug fixes only.

**Comment by MaximWain** [comment]
Sir , if you help me i can pay yours work , 
i really like Gazelle, I ask lots peoples. all are not help :( , So Kindly help me. Thanks you

**Comment by WhatCD** [comment]
We do not offer any services related to gazelle. There are plenty of places on the internet to find freelance programmers you may pay to solve your problem. Good luck.
