### ISSUE TITLE
Impossible to log in to what.cd

### ISSUE THREAD

**Issue by GioBleaux** [WhatCD/Gazelle#85]
To be brief, I've got a password (a couple of years old) for **what.cd**. But every time I try to log in (either with, or without using a VPN) using Firefox 39.0.3, just clicking **Log In** returns the following message:

>**Error**
>Your IP address has been banned.​

Ideas?

**Comment by Steinies** [comment]
Maybe try to contact the support via IRC.
This is not a place to ask for it.

**Comment by WhatCD** [comment]
If you need help with logging in, please join #what.cd-disabled on irc.what-network.net.
